places = ['Paris', 'Amsterdam', 'Vegas', 'Asia', 'Japan']
print(f"Original list: {places}")
print(f"With sorted: {sorted(places)}")
print(f"Unchanged list: {places}")
print(f"Reverse alphabetical: {sorted(places, reverse=True)}")
print(f"Unchanged list: {places}")
places.reverse()
print(f"Original list reversed: {places}")
places.reverse()
print(f"Original list reversed again: {places}")
places.sort()
print(f"Original list changed (alpha): {places}")
places.sort(reverse=True)
print(f"Original list chaged (reverse-alpha): {places}")
